[package]
name = "sawtooth_validator"
version = "1.1.0"
authors = ["Intel Corporation"]

[dependencies]
clap = "2"
cpython = "0.2"
log = { version = "0.4", features = ["std"] }
libc = ">=0.2.35"
lmdb-zero = ">=0.4.1"
cbor-codec = "0.7"
rust-crypto = "0.2"

[dev-dependencies]
rand = "0.4"

[lib]
crate-type = ["dylib"]

[[bin]]
name = "sawtooth-validator"
path = "src/main.rs"
